### ISSUE TITLE
airbrake 로깅 추가

### ISSUE THREAD

**Issue by kwangkuk0821** [croquiscom/Crary-Node#27]
# Context
airbrake(https://airbrake.io/)

에러 관리를 위해, Airbrake 서비스를 시험적으로 도입해볼 예정입니다.
Express 에서 발생하는 Error 를 Airbrake 에서 추적하기 위해,
Crary Express 에 Airbrake 코드를 삽입합니다.

**Comment by sixmen** [comment]
airbrake를 사용하지 않는 것으로 했습니다
